# Generated by Django 4.1.5 on 2023-01-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_rename_name_course_coursename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseName',
            new_name='name',
        ),
    ]
