# Generated by Django 4.1.5 on 2023-01-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
