# Generated by Django 4.1.5 on 2023-01-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Adress'),
        ),
        migrations.AddField(
            model_name='student',
            name='fatherName',
            field=models.CharField(max_length=100, null=True, verbose_name='Father Name'),
        ),
    ]
