# Generated by Django 4.1.5 on 2023-01-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_address_student_fathername'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_course',
            old_name='course_id',
            new_name='Course_id',
        ),
        migrations.RenameField(
            model_name='student_course',
            old_name='student_id',
            new_name='Student_id',
        ),
    ]
