# Generated by Django 4.1.5 on 2023-01-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_remove_course_students'),
        ('student', '0007_rename_course_id_student_course_courseid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_course',
            new_name='StudentCourse',
        ),
    ]
