# Generated by Django 4.1.5 on 2023-01-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_rename_student_course_studentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Adress'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fatherName',
            field=models.CharField(max_length=50, null=True, verbose_name='Father Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Student Name'),
        ),
    ]
